set guifont=Inconsolata\ for\ Powerline:h16.00

" scrollbar disabled
set guioptions-=rL
set guioptions-=e


"disable autostart of nerdtree
let g:nerdtree_tabs_open_on_gui_startup=0

hi StatusLine guibg=white guifg=black

colorscheme my-hybrid
