source ~/dotfiles/zsh/checks.zsh
source ~/dotfiles/zsh/colors.zsh
source ~/dotfiles/zsh/setopt.zsh
source ~/dotfiles/zsh/exports.zsh
source ~/dotfiles/zsh/promptTools.zsh
source ~/dotfiles/zsh/promptTwoLine.zsh
source ~/dotfiles/zsh/completion.zsh
source ~/dotfiles/zsh/aliases.zsh
source ~/dotfiles/zsh/bindkeys.zsh
source ~/dotfiles/zsh/functions.zsh
source ~/dotfiles/zsh/history.zsh
source ~/dotfiles/zsh/zsh_hooks.zsh

# add custom Completion
fpath=(~/dotfiles/zsh/completion $fpath)

# compsys initialization
autoload -U compinit
compinit

#important for autojump to work properly
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# enable vim mode
bindkey -v
export KEYTIMEOUT=1

function print_dcs
{
  print -n -- "\EP$1;\E$2\E\\"
}

function set_cursor_shape
{
  if [ -n "$TMUX" ]; then
    # tmux will only forward escape sequences to the terminal if surrounded by
    # a DCS sequence
    print_dcs tmux "\E]50;CursorShape=$1\C-G"
  else
    print -n -- "\E]50;CursorShape=$1\C-G"
  fi
}

function zle-keymap-select zle-line-init
{
  case $KEYMAP in
    vicmd)
      set_cursor_shape 0 # block cursor
      ;;
    viins|main)
      set_cursor_shape 1 # line cursor
      ;;
  esac
  zle reset-prompt
  zle -R
}

function zle-line-finish
{
  set_cursor_shape 0 # block cursor
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

# vim:set ft=zsh:

bindkey -v
